# Generated by Django 6.1.1 on 2026-09-19 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=7)),
                ('monto_bolivares', models.DecimalField(decimal_places=2, max_digits=7)),
                ('monto_usd', models.DecimalField(decimal_places=2, max_digits=7)),
                ('estado_actual', models.CharField(choices=[('registrado', 'Registrado'), ('cancelado', 'Cancelado'), ('en_transito', 'En Transito'), ('disponible', 'Disponible'), ('entregado', 'Entregado'), ('extraviado', 'Extraviado'), ('en_agencia', 'En Agencia')], default='registrado', max_length=50)),
                ('agencia_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio_agencia_destino', to='ubicaciones.agencia')),
                ('agencia_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envio_agencia_origen', to='ubicaciones.agencia')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinatarios', to=settings.AUTH_USER_MODEL)),
                ('remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitentes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('registrado', 'Registrado'), ('cancelado', 'Cancelado'), ('en_transito', 'En Transito'), ('disponible', 'Disponible'), ('entregado', 'Entregado'), ('extraviado', 'Extraviado'), ('en_agencia', 'En Agencia')], default='registrado', max_length=50)),
                ('observacion', models.TextField()),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('actualiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='encomiendas.guiaenvio')),
            ],
        ),
    ]
