# Generated by Django 6.1.1 on 2026-09-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encomiendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guiaenvio',
            name='numero_guia',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
